### ISSUE TITLE
Running Eudico with Mir triggers a panic: type assertion error

### ISSUE THREAD

**Issue by dnkolegov** [filecoin-project/mir#24]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x105a4a7c4]

goroutine 15 [running]:
github.com/filecoin-project/mir.(*workItems).AddEvents(0x140020af1c0, 0x140001ee120?)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220422110819-f38593bae779/workitems.go:86 +0x154
github.com/filecoin-project/mir.(*Node).processWAL(0x14000e6e400)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220422110819-f38593bae779/node.go:214 +0xe0
github.com/filecoin-project/mir.(*Node).Run(0x14000e6e400, {0x107fc4348, 0x14000dc0880}, 0x140010f62a0?)
	/Users/alpha/go/pkg/mod/github.com/filecoin-project/mir@v0.0.0-20220422110819-f38593bae779/node.go:182 +0x3c
github.com/filecoin-project/lotus/chain/consensus/mir.(*MirAgent).Start.func2()
	/Users/alpha/Projects/eudico/chain/consensus/mir/mir_agent.go:143 +0x6c
created by github.com/filecoin-project/lotus/chain/consensus/mir.(*MirAgent).Start
	/Users/alpha/Projects/eudico/chain/consensus/mir/mir_agent.go:142 +0x1d8

[Line 86](https://github.com/filecoin-project/mir/blob/main/workitems.go#L86) performs the type assertion operation without checking if type assertion holds or not.

If the type assertion is false, a [run-time panic](https://golang.org/ref/spec#Run_time_panics) occurs.

The result of type assertion is not checked systematically. I believe we MUST enforce this check everywhere in MIR.

**Comment by matejpavlovic** [comment]
It doesn't look like a failed type assertion, at least the referenced Line 86 does not seem to contain one. To me it looks more like the value of either `WalEntry` or `Event` is nil (and we try to dereference it)...

**Comment by dnkolegov** [comment]
This panic happens if I run a client two times and do not remove WAL's files after the first run.

**Comment by dnkolegov** [comment]
We should address the panic problem in Mir. 
The core of the Mir mustn't panic, probably. Especially, when it handles input data controlled by an external agent.

**Comment by matejpavlovic** [comment]
Yes, agree, Mir core must not panic. The current panic is caused by the loading of the WAL on startup not yet being implemented. A node starts and tries to load the WAL in order to rebuild its state, but that logic is not yet properly present.

We will implement that when dealing with restarts. For now, as a temporary measure, the WAL module can be completely disabled by simply not instantiating it when creating a Mir Node with `mir.NewNode()`.

**Comment by dnkolegov** [comment]
I erase WAL files each restart

**Comment by matejpavlovic** [comment]
Mir is not being used with Eudico any more and neither is the WAL with Mir.
